/** Declaration file generated by dts-gen */
// tslint:disable
export function decodeLog(inputs: any, data: any, topics: any): any;

export function decodeParameter(type: any, bytes: any): any;

export function decodeParameters(outputs: any, bytes: any): any;

export function encodeEventSignature(functionName: any): any;

export function encodeFunctionCall(jsonInterface: any, params: any): any;

export function encodeFunctionSignature(functionName: any): any;

export function encodeParameter(type: any, param: any): any;

export function encodeParameters(types: any, params: any): any;

export function isSimplifiedStructFormat(type: any): any;

export function mapStructNameAndType(structName: any): any;

export function mapStructToCoderFormat(struct: any): any;

export function mapTypes(types: any): any;

export namespace decodeLog {
    const prototype: {
    };

}

export namespace decodeParameter {
    const prototype: {
    };

}

export namespace decodeParameters {
    const prototype: {
    };

}

export namespace encodeEventSignature {
    const prototype: {
    };

}

export namespace encodeFunctionCall {
    const prototype: {
    };

}

export namespace encodeFunctionSignature {
    const prototype: {
    };

}

export namespace encodeParameter {
    const prototype: {
    };

}

export namespace encodeParameters {
    const prototype: {
    };

}

export namespace isSimplifiedStructFormat {
    const prototype: {
    };

}

export namespace mapStructNameAndType {
    const prototype: {
    };

}

export namespace mapStructToCoderFormat {
    const prototype: {
    };

}

export namespace mapTypes {
    const prototype: {
    };

}
